#Pandas Tutorial From Code With Harry

In [1]:
import numpy as np
import pandas as pd

In [5]:
dict1={
    "name":['hasrsh','A','B','c'],
    "marks":[92,34,24,17],
    "city":['rampur','kolkata','bareilly','antarctica']
}

In [6]:
df=pd.DataFrame(dict1)

In [7]:
df

     name  marks        city
0  hasrsh     92      rampur
1       A     34     kolkata
2       B     24    bareilly
3       c     17  antarctica

In [8]:
df.to_csv('friends.csv')

In [10]:
df.to_csv('friends_index_false.csv' , index=False)

In [11]:
df.head(2)

     name  marks     city
0  hasrsh     92   rampur
1       A     34  kolkata

In [12]:
df.tail()

     name  marks        city
0  hasrsh     92      rampur
1       A     34     kolkata
2       B     24    bareilly
3       c     17  antarctica

In [13]:
df.describe()

          marks
count   4.00000
mean   41.75000
std    34.21866
min    17.00000
25%    22.25000
50%    29.00000
75%    48.50000
max    92.00000

In [14]:
harsh=pd.read_csv('Harsh.csv')

In [15]:
harsh

   Unnamed: 0    name  marks        city
0           0  hasrsh     92      rampur
1           1       A     34     kolkata
2           2       B     24    bareilly
3           3       c     17  antarctica

In [17]:
harsh['marks'][0]=50

/var/folders/8y/st09g56d7_zdd67wcxcy08v80000gn/T/ipykernel_64624/3080940341.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  harsh['marks'][0]=50
/var/folders/8y/st09g56d7_zdd67wcxcy08v80000gn/T/ipykernel_64624/3080940341.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  harsh['marks'][0]=50

In [18]:
harsh

   Unnamed: 0    name  marks        city
0           0  hasrsh     50      rampur
1           1       A     34     kolkata
2           2       B     24    bareilly
3           3       c     17  antarctica

In [19]:
harsh.to_csv('harsh.csv')

In [20]:
harsh.index=['first','second','third','fourth']

In [21]:
harsh

        Unnamed: 0    name  marks        city
first            0  hasrsh     50      rampur
second           1       A     34     kolkata
third            2       B     24    bareilly
fourth           3       c     17  antarctica

In [ ]:
ser=pd.Series(np.random.rand(34))

In [24]:
type(ser)

pandas.core.series.Series

In [26]:
newdf=pd.DataFrame(np.random.rand(334,5) , index=np.arange(334))

In [28]:
type(newdf)

pandas.core.frame.DataFrame

In [29]:
newdf.describe()

                0           1           2           3           4
count  334.000000  334.000000  334.000000  334.000000  334.000000
mean     0.477109    0.502583    0.490012    0.496008    0.479647
std      0.283555    0.295186    0.280172    0.286797    0.290101
min      0.003556    0.003397    0.008742    0.001237    0.003411
25%      0.238084    0.236398    0.242407    0.248578    0.227133
50%      0.449382    0.487508    0.497414    0.485181    0.464687
75%      0.712396    0.744370    0.699687    0.750730    0.725992
max      0.997624    0.993679    0.999391    0.999926    0.997366

In [30]:
newdf.dtypes

0    float64
1    float64
2    float64
3    float64
4    float64
dtype: object

In [31]:
newdf.head()

          0         1         2         3         4
0  0.014476  0.716000  0.048717  0.732332  0.455069
1  0.771128  0.407939  0.999391  0.168867  0.856299
2  0.827765  0.597153  0.471384  0.601813  0.500527
3  0.313792  0.519650  0.595002  0.883462  0.639246
4  0.520915  0.219970  0.443246  0.214219  0.762731

In [32]:
newdf[0][0]="harsh"

/var/folders/8y/st09g56d7_zdd67wcxcy08v80000gn/T/ipykernel_64624/347663834.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  newdf[0][0]="harsh"
/var/folders/8y/st09g56d7_zdd67wcxcy08v80000gn/T/ipykernel_64624/347663834.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'harsh' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  newdf[0][0]="harsh"

In [33]:
newdf

            0         1         2         3         4
0       harsh  0.716000  0.048717  0.732332  0.455069
1    0.771128  0.407939  0.999391  0.168867  0.856299
2    0.827765  0.597153  0.471384  0.601813  0.500527
3    0.313792  0.519650  0.595002  0.883462  0.639246
4    0.520915  0.219970  0.443246  0.214219  0.762731
..        ...       ...       ...       ...       ...
329  0.871153  0.105250  0.517251  0.460872  0.995609
330  0.777852  0.345356  0.911827  0.158502  0.381520
331  0.093108  0.926849  0.161260  0.654912  0.276859
332  0.867334  0.373486  0.282610  0.120285  0.364141
333  0.620655  0.604046  0.265880  0.072433  0.692164

[334 rows x 5 columns]

In [35]:
newdf.dtypes

0     object
1    float64
2    float64
3    float64
4    float64
dtype: object

In [36]:
newdf.index

Index([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,
       ...
       324, 325, 326, 327, 328, 329, 330, 331, 332, 333],
      dtype='int64', length=334)

In [37]:
newdf.columns

RangeIndex(start=0, stop=5, step=1)

In [38]:
newdf.to_numpy

<bound method DataFrame.to_numpy of             0         1         2         3         4
0       harsh  0.716000  0.048717  0.732332  0.455069
1    0.771128  0.407939  0.999391  0.168867  0.856299
2    0.827765  0.597153  0.471384  0.601813  0.500527
3    0.313792  0.519650  0.595002  0.883462  0.639246
4    0.520915  0.219970  0.443246  0.214219  0.762731
..        ...       ...       ...       ...       ...
329  0.871153  0.105250  0.517251  0.460872  0.995609
330  0.777852  0.345356  0.911827  0.158502  0.381520
331  0.093108  0.926849  0.161260  0.654912  0.276859
332  0.867334  0.373486  0.282610  0.120285  0.364141
333  0.620655  0.604046  0.265880  0.072433  0.692164

[334 rows x 5 columns]>

In [39]:
newdf[0][0]=0.344

In [40]:
newdf

            0         1         2         3         4
0       0.344  0.716000  0.048717  0.732332  0.455069
1    0.771128  0.407939  0.999391  0.168867  0.856299
2    0.827765  0.597153  0.471384  0.601813  0.500527
3    0.313792  0.519650  0.595002  0.883462  0.639246
4    0.520915  0.219970  0.443246  0.214219  0.762731
..        ...       ...       ...       ...       ...
329  0.871153  0.105250  0.517251  0.460872  0.995609
330  0.777852  0.345356  0.911827  0.158502  0.381520
331  0.093108  0.926849  0.161260  0.654912  0.276859
332  0.867334  0.373486  0.282610  0.120285  0.364141
333  0.620655  0.604046  0.265880  0.072433  0.692164

[334 rows x 5 columns]

In [42]:
newdf.to_numpy()

array([[0.344, 0.7160002641336441, 0.0487167182618895,
        0.7323321575320623, 0.4550690376371712],
       [0.7711275704038748, 0.40793885911337757, 0.9993911439264868,
        0.16886652586496687, 0.8562990217631384],
       [0.8277646165435758, 0.5971525361019993, 0.4713843495341644,
        0.6018132145358793, 0.500526654358782],
       ...,
       [0.09310817979360475, 0.9268485069658748, 0.16125998580787937,
        0.6549123198653818, 0.2768590536990163],
       [0.8673339248033466, 0.3734856690686035, 0.282609833979667,
        0.12028465844506897, 0.36414138273522734],
       [0.6206551446792293, 0.6040457420791918, 0.2658803152048592,
        0.07243327025570967, 0.692164262204158]],
      shape=(334, 5), dtype=object)

In [43]:
newdf.T

,0,1,2,3,4,5,6,7,8,9,...,324,325,326,327,328,329,330,331,332,333
0,0.344,0.771128,0.827765,0.313792,0.520915,0.970207,0.564658,0.427014,0.31358,0.348471,...,0.876783,0.506968,0.58002,0.360012,0.157325,0.871153,0.777852,0.093108,0.867334,0.620655
1,0.716,0.407939,0.597153,0.51965,0.21997,0.438316,0.852282,0.292861,0.917774,0.944632,...,0.02801,0.682314,0.604299,0.797958,0.322867,0.10525,0.345356,0.926849,0.373486,0.604046
2,0.048717,0.999391,0.471384,0.595002,0.443246,0.051464,0.825172,0.831903,0.572933,0.278777,...,0.637269,0.648417,0.149591,0.208751,0.480147,0.517251,0.911827,0.16126,0.28261,0.26588
3,0.732332,0.168867,0.601813,0.883462,0.214219,0.725922,0.559532,0.684922,0.557301,0.940199,...,0.110064,0.065342,0.911133,0.755213,0.297647,0.460872,0.158502,0.654912,0.120285,0.072433
4,0.455069,0.856299,0.500527,0.639246,0.762731,0.811292,0.428523,0.972355,0.205522,0.748164,...,0.588782,0.310021,0.069468,0.720694,0.237211,0.995609,0.38152,0.276859,0.364141,0.692164

In [44]:
newdf

            0         1         2         3         4
0       0.344  0.716000  0.048717  0.732332  0.455069
1    0.771128  0.407939  0.999391  0.168867  0.856299
2    0.827765  0.597153  0.471384  0.601813  0.500527
3    0.313792  0.519650  0.595002  0.883462  0.639246
4    0.520915  0.219970  0.443246  0.214219  0.762731
..        ...       ...       ...       ...       ...
329  0.871153  0.105250  0.517251  0.460872  0.995609
330  0.777852  0.345356  0.911827  0.158502  0.381520
331  0.093108  0.926849  0.161260  0.654912  0.276859
332  0.867334  0.373486  0.282610  0.120285  0.364141
333  0.620655  0.604046  0.265880  0.072433  0.692164

[334 rows x 5 columns]

In [45]:
newdf.head()

          0         1         2         3         4
0     0.344  0.716000  0.048717  0.732332  0.455069
1  0.771128  0.407939  0.999391  0.168867  0.856299
2  0.827765  0.597153  0.471384  0.601813  0.500527
3  0.313792  0.519650  0.595002  0.883462  0.639246
4  0.520915  0.219970  0.443246  0.214219  0.762731

In [46]:
newdf.sort_index(axis=0 , ascending=False)

            0         1         2         3         4
333  0.620655  0.604046  0.265880  0.072433  0.692164
332  0.867334  0.373486  0.282610  0.120285  0.364141
331  0.093108  0.926849  0.161260  0.654912  0.276859
330  0.777852  0.345356  0.911827  0.158502  0.381520
329  0.871153  0.105250  0.517251  0.460872  0.995609
..        ...       ...       ...       ...       ...
4    0.520915  0.219970  0.443246  0.214219  0.762731
3    0.313792  0.519650  0.595002  0.883462  0.639246
2    0.827765  0.597153  0.471384  0.601813  0.500527
1    0.771128  0.407939  0.999391  0.168867  0.856299
0       0.344  0.716000  0.048717  0.732332  0.455069

[334 rows x 5 columns]

In [47]:
newdf.sort_index(axis=1 , ascending=False)

            4         3         2         1         0
0    0.455069  0.732332  0.048717  0.716000     0.344
1    0.856299  0.168867  0.999391  0.407939  0.771128
2    0.500527  0.601813  0.471384  0.597153  0.827765
3    0.639246  0.883462  0.595002  0.519650  0.313792
4    0.762731  0.214219  0.443246  0.219970  0.520915
..        ...       ...       ...       ...       ...
329  0.995609  0.460872  0.517251  0.105250  0.871153
330  0.381520  0.158502  0.911827  0.345356  0.777852
331  0.276859  0.654912  0.161260  0.926849  0.093108
332  0.364141  0.120285  0.282610  0.373486  0.867334
333  0.692164  0.072433  0.265880  0.604046  0.620655

[334 rows x 5 columns]

In [48]:
newdf.head()

          0         1         2         3         4
0     0.344  0.716000  0.048717  0.732332  0.455069
1  0.771128  0.407939  0.999391  0.168867  0.856299
2  0.827765  0.597153  0.471384  0.601813  0.500527
3  0.313792  0.519650  0.595002  0.883462  0.639246
4  0.520915  0.219970  0.443246  0.214219  0.762731

In [49]:
newdf[0]

0         0.344
1      0.771128
2      0.827765
3      0.313792
4      0.520915
         ...
329    0.871153
330    0.777852
331    0.093108
332    0.867334
333    0.620655
Name: 0, Length: 334, dtype: object

In [51]:
type(newdf[0])

pandas.core.series.Series

In [52]:
newdf2=newdf

In [53]:
newdf2[0][0]=34242

In [54]:
newdf

            0         1         2         3         4
0       34242  0.716000  0.048717  0.732332  0.455069
1    0.771128  0.407939  0.999391  0.168867  0.856299
2    0.827765  0.597153  0.471384  0.601813  0.500527
3    0.313792  0.519650  0.595002  0.883462  0.639246
4    0.520915  0.219970  0.443246  0.214219  0.762731
..        ...       ...       ...       ...       ...
329  0.871153  0.105250  0.517251  0.460872  0.995609
330  0.777852  0.345356  0.911827  0.158502  0.381520
331  0.093108  0.926849  0.161260  0.654912  0.276859
332  0.867334  0.373486  0.282610  0.120285  0.364141
333  0.620655  0.604046  0.265880  0.072433  0.692164

[334 rows x 5 columns]

In [55]:
newdf2

            0         1         2         3         4
0       34242  0.716000  0.048717  0.732332  0.455069
1    0.771128  0.407939  0.999391  0.168867  0.856299
2    0.827765  0.597153  0.471384  0.601813  0.500527
3    0.313792  0.519650  0.595002  0.883462  0.639246
4    0.520915  0.219970  0.443246  0.214219  0.762731
..        ...       ...       ...       ...       ...
329  0.871153  0.105250  0.517251  0.460872  0.995609
330  0.777852  0.345356  0.911827  0.158502  0.381520
331  0.093108  0.926849  0.161260  0.654912  0.276859
332  0.867334  0.373486  0.282610  0.120285  0.364141
333  0.620655  0.604046  0.265880  0.072433  0.692164

[334 rows x 5 columns]

In [56]:
newdf2=newdf.copy()

In [57]:
newdf2[0][0]=3123131

/var/folders/8y/st09g56d7_zdd67wcxcy08v80000gn/T/ipykernel_64624/2513800795.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  newdf2[0][0]=3123131
/var/folders/8y/st09g56d7_zdd67wcxcy08v80000gn/T/ipykernel_64624/2513800795.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  newdf2[0][0]=3123131

In [58]:
newdf

            0         1         2         3         4
0       34242  0.716000  0.048717  0.732332  0.455069
1    0.771128  0.407939  0.999391  0.168867  0.856299
2    0.827765  0.597153  0.471384  0.601813  0.500527
3    0.313792  0.519650  0.595002  0.883462  0.639246
4    0.520915  0.219970  0.443246  0.214219  0.762731
..        ...       ...       ...       ...       ...
329  0.871153  0.105250  0.517251  0.460872  0.995609
330  0.777852  0.345356  0.911827  0.158502  0.381520
331  0.093108  0.926849  0.161260  0.654912  0.276859
332  0.867334  0.373486  0.282610  0.120285  0.364141
333  0.620655  0.604046  0.265880  0.072433  0.692164

[334 rows x 5 columns]

In [59]:
newdf2

            0         1         2         3         4
0     3123131  0.716000  0.048717  0.732332  0.455069
1    0.771128  0.407939  0.999391  0.168867  0.856299
2    0.827765  0.597153  0.471384  0.601813  0.500527
3    0.313792  0.519650  0.595002  0.883462  0.639246
4    0.520915  0.219970  0.443246  0.214219  0.762731
..        ...       ...       ...       ...       ...
329  0.871153  0.105250  0.517251  0.460872  0.995609
330  0.777852  0.345356  0.911827  0.158502  0.381520
331  0.093108  0.926849  0.161260  0.654912  0.276859
332  0.867334  0.373486  0.282610  0.120285  0.364141
333  0.620655  0.604046  0.265880  0.072433  0.692164

[334 rows x 5 columns]

In [60]:
newdf.loc[0,0]=654

In [61]:
newdf.head()

          0         1         2         3         4
0       654  0.716000  0.048717  0.732332  0.455069
1  0.771128  0.407939  0.999391  0.168867  0.856299
2  0.827765  0.597153  0.471384  0.601813  0.500527
3  0.313792  0.519650  0.595002  0.883462  0.639246
4  0.520915  0.219970  0.443246  0.214219  0.762731

In [62]:
newdf.columns=list("ABCDE")

In [63]:
newdf

            A         B         C         D         E
0         654  0.716000  0.048717  0.732332  0.455069
1    0.771128  0.407939  0.999391  0.168867  0.856299
2    0.827765  0.597153  0.471384  0.601813  0.500527
3    0.313792  0.519650  0.595002  0.883462  0.639246
4    0.520915  0.219970  0.443246  0.214219  0.762731
..        ...       ...       ...       ...       ...
329  0.871153  0.105250  0.517251  0.460872  0.995609
330  0.777852  0.345356  0.911827  0.158502  0.381520
331  0.093108  0.926849  0.161260  0.654912  0.276859
332  0.867334  0.373486  0.282610  0.120285  0.364141
333  0.620655  0.604046  0.265880  0.072433  0.692164

[334 rows x 5 columns]

In [67]:
newdf.loc[0,'A']=653422344

In [68]:
newdf

             A         B         C         D         E      0
0    653422344  0.716000  0.048717  0.732332  0.455069  654.0
1     0.771128  0.407939  0.999391  0.168867  0.856299    NaN
2     0.827765  0.597153  0.471384  0.601813  0.500527    NaN
3     0.313792  0.519650  0.595002  0.883462  0.639246    NaN
4     0.520915  0.219970  0.443246  0.214219  0.762731    NaN
..         ...       ...       ...       ...       ...    ...
329   0.871153  0.105250  0.517251  0.460872  0.995609    NaN
330   0.777852  0.345356  0.911827  0.158502  0.381520    NaN
331   0.093108  0.926849  0.161260  0.654912  0.276859    NaN
332   0.867334  0.373486  0.282610  0.120285  0.364141    NaN
333   0.620655  0.604046  0.265880  0.072433  0.692164    NaN

[334 rows x 6 columns]

In [72]:
newdf=newdf.drop(0,axis=1)

In [73]:
newdf.head()

           A         B         C         D         E
0  653422344  0.716000  0.048717  0.732332  0.455069
1   0.771128  0.407939  0.999391  0.168867  0.856299
2   0.827765  0.597153  0.471384  0.601813  0.500527
3   0.313792  0.519650  0.595002  0.883462  0.639246
4   0.520915  0.219970  0.443246  0.214219  0.762731

In [74]:
newdf.loc[[1,2],['C','D']]

          C         D
1  0.999391  0.168867
2  0.471384  0.601813

In [75]:
newdf.head()

           A         B         C         D         E
0  653422344  0.716000  0.048717  0.732332  0.455069
1   0.771128  0.407939  0.999391  0.168867  0.856299
2   0.827765  0.597153  0.471384  0.601813  0.500527
3   0.313792  0.519650  0.595002  0.883462  0.639246
4   0.520915  0.219970  0.443246  0.214219  0.762731

In [76]:
newdf.loc[[1,2],:]

          A         B         C         D         E
1  0.771128  0.407939  0.999391  0.168867  0.856299
2  0.827765  0.597153  0.471384  0.601813  0.500527

In [77]:
newdf.loc[:,['C','D']]

            C         D
0    0.048717  0.732332
1    0.999391  0.168867
2    0.471384  0.601813
3    0.595002  0.883462
4    0.443246  0.214219
..        ...       ...
329  0.517251  0.460872
330  0.911827  0.158502
331  0.161260  0.654912
332  0.282610  0.120285
333  0.265880  0.072433

[334 rows x 2 columns]

In [81]:
newdf.loc[(newdf['A']<0.3) & (newdf['C']>0.1)]

            A         B         C         D         E
11   0.003556  0.867685  0.895542  0.950754  0.698057
13   0.151111  0.173447  0.851569  0.738980  0.021911
16    0.28254  0.440070  0.654457  0.212706  0.011434
17   0.191332  0.341616  0.354368  0.589520  0.164521
18   0.242058  0.820017  0.485865  0.254012  0.419800
..        ...       ...       ...       ...       ...
317  0.236039  0.615081  0.673492  0.904665  0.463646
322  0.255107  0.547391  0.696393  0.400404  0.977033
323  0.234896  0.762547  0.973936  0.260188  0.975906
328  0.157325  0.322867  0.480147  0.297647  0.237211
331  0.093108  0.926849  0.161260  0.654912  0.276859

[96 rows x 5 columns]

In [82]:
newdf.iloc[0,4]

np.float64(0.4550690376371712)

In [84]:
newdf.head(2)

           A         B         C         D         E
0  653422344  0.716000  0.048717  0.732332  0.455069
1   0.771128  0.407939  0.999391  0.168867  0.856299

In [85]:
newdf.iloc[[0,1],[1,2]]

          B         C
0  0.716000  0.048717
1  0.407939  0.999391

In [86]:
newdf.head(3)

           A         B         C         D         E
0  653422344  0.716000  0.048717  0.732332  0.455069
1   0.771128  0.407939  0.999391  0.168867  0.856299
2   0.827765  0.597153  0.471384  0.601813  0.500527

In [87]:
newdf.drop([0])

            A         B         C         D         E
1    0.771128  0.407939  0.999391  0.168867  0.856299
2    0.827765  0.597153  0.471384  0.601813  0.500527
3    0.313792  0.519650  0.595002  0.883462  0.639246
4    0.520915  0.219970  0.443246  0.214219  0.762731
5    0.970207  0.438316  0.051464  0.725922  0.811292
..        ...       ...       ...       ...       ...
329  0.871153  0.105250  0.517251  0.460872  0.995609
330  0.777852  0.345356  0.911827  0.158502  0.381520
331  0.093108  0.926849  0.161260  0.654912  0.276859
332  0.867334  0.373486  0.282610  0.120285  0.364141
333  0.620655  0.604046  0.265880  0.072433  0.692164

[333 rows x 5 columns]

In [92]:
newdf.drop([1,5],axis=0 , inplace=True)

In [93]:
newdf

            B         D         E
0    0.716000  0.732332  0.455069
2    0.597153  0.601813  0.500527
3    0.519650  0.883462  0.639246
4    0.219970  0.214219  0.762731
6    0.852282  0.559532  0.428523
..        ...       ...       ...
329  0.105250  0.460872  0.995609
330  0.345356  0.158502  0.381520
331  0.926849  0.654912  0.276859
332  0.373486  0.120285  0.364141
333  0.604046  0.072433  0.692164

[332 rows x 3 columns]

In [96]:
newdf.reset_index(drop=True,inplace=True)

In [97]:
newdf

            B         D         E
0    0.716000  0.732332  0.455069
1    0.597153  0.601813  0.500527
2    0.519650  0.883462  0.639246
3    0.219970  0.214219  0.762731
4    0.852282  0.559532  0.428523
..        ...       ...       ...
327  0.105250  0.460872  0.995609
328  0.345356  0.158502  0.381520
329  0.926849  0.654912  0.276859
330  0.373486  0.120285  0.364141
331  0.604046  0.072433  0.692164

[332 rows x 3 columns]

In [98]:
newdf['B'].isnull()

0      False
1      False
2      False
3      False
4      False
       ...
327    False
328    False
329    False
330    False
331    False
Name: B, Length: 332, dtype: bool

In [99]:
newdf['B']=None

In [100]:
newdf

        B         D         E
0    None  0.732332  0.455069
1    None  0.601813  0.500527
2    None  0.883462  0.639246
3    None  0.214219  0.762731
4    None  0.559532  0.428523
..    ...       ...       ...
327  None  0.460872  0.995609
328  None  0.158502  0.381520
329  None  0.654912  0.276859
330  None  0.120285  0.364141
331  None  0.072433  0.692164

[332 rows x 3 columns]

In [103]:
newdf.loc[:,['B']]=34

In [104]:
newdf['B'].isnull()

0      False
1      False
2      False
3      False
4      False
       ...
327    False
328    False
329    False
330    False
331    False
Name: B, Length: 332, dtype: bool

In [105]:
df=pd.DataFrame({
    "name": ["Alice", "Bob", "Charlie"],
    "toy": ["Teddy Bear", "Toy Car", "Lego Set"],
    "born": [2015, 2016, 2014]
})

In [106]:
df.head()

      name         toy  born
0    Alice  Teddy Bear  2015
1      Bob     Toy Car  2016
2  Charlie    Lego Set  2014

In [107]:
df.dropna()

      name         toy  born
0    Alice  Teddy Bear  2015
1      Bob     Toy Car  2016
2  Charlie    Lego Set  2014

In [109]:
df.shape

(3, 3)

In [110]:
df.info

<bound method DataFrame.info of       name         toy  born
0    Alice  Teddy Bear  2015
1      Bob     Toy Car  2016
2  Charlie    Lego Set  2014>

In [111]:
df['name'].value_counts(dropna=False)

name
Alice      1
Bob        1
Charlie    1
Name: count, dtype: int64

In [112]:
df.notnull()

   name   toy  born
0  True  True  True
1  True  True  True
2  True  True  True