In [3]:
import numpy as np
import pandas as pd

#Questiond

###Q1 Write a Python program to create and display a one-dimensional array-like object
containing an array of data using Pandas module.

In [6]:
dict={
    "Name" : ['A','B','C','D'],
    "Age" : ['12','13','14','15'],
    "City" : ['Agra','Delhi','Haryana','Gurgao']
}
df=pd.DataFrame(dict)
df

  Name Age     City
0    A  12     Agra
1    B  13    Delhi
2    C  14  Haryana
3    D  15   Gurgao

In [7]:
arr=[1,23,4,5,6]
df=pd.Series(arr)
df

0     1
1    23
2     4
3     5
4     6
dtype: int64

###Q2 Write a Python program to convert a Panda module Series to Python list and it's type.

In [11]:
df=pd.Series(arr)
print(df)
print(type(df))
print(df.tolist())

0     1
1    23
2     4
3     5
4     6
dtype: int64
<class 'pandas.core.series.Series'>
[1, 23, 4, 5, 6]

###Q3 Write a Python program to add, subtract, multiple and divide two Pandas Series.

In [12]:
ar1=[2, 4, 6, 8, 10]
ar2=[1, 3, 5, 7, 9]
d1=pd.Series(ar1)
d2=pd.Series(ar2)
print("Add")
print(d1+d2)
print("Subtract")
print(d1-d2)
print("Multiply")
print(d1*d2)
print("Divide")
print(d1/d2)

Add
0     3
1     7
2    11
3    15
4    19
dtype: int64
Subtract
0    1
1    1
2    1
3    1
4    1
dtype: int64
Multiply
0     2
1    12
2    30
3    56
4    90
dtype: int64
Divide
0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64

###Q4 Write a Python program to get the powers of an array values element-wise

###Q5 Write a Python program to create and display a DataFrame from a specified dictionary
data which has the index labels.

In [5]:
exam_data = {'name': ['Anastasia','Dima','Matthew','Laura','Kevin','Jonas','Katherine','James','Emily','Michael'],
'score': [12.5, 9, 16.5,'NA', 9, 20, 14.5, 'NA', 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes','no','yes','no','no','yes','yes','no','no','yes']}
labels = ['a','b','c','d','e','f','g','h','i','j']
df=pd.DataFrame(exam_data,index=labels)
df

        name score  attempts qualify
a  Anastasia  12.5         1     yes
b       Dima     9         3      no
c    Matthew  16.5         2     yes
d      Laura    NA         3      no
e      Kevin     9         2      no
f      Jonas    20         3     yes
g  Katherine  14.5         1     yes
h      James    NA         1      no
i      Emily     8         2      no
j    Michael    19         1     yes

###Q6 Write a Python program to display a summary of the basic information about a
specified Data Frame and its data.

In [7]:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew',
'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
df=pd.DataFrame(exam_data,index=labels)
print("Information")
print(df.info())
print("Description")
print(df.describe())

Information
<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, a to j
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   name      10 non-null     object
 1   score     8 non-null      float64
 2   attempts  10 non-null     int64
 3   qualify   10 non-null     object
dtypes: float64(1), int64(1), object(2)
memory usage: 400.0+ bytes
None
Description
           score   attempts
count   8.000000  10.000000
mean   13.562500   1.900000
std     4.693746   0.875595
min     8.000000   1.000000
25%     9.000000   1.000000
50%    13.500000   2.000000
75%    17.125000   2.750000
max    20.000000   3.000000

###Q7 Write a Python program to get the first 3 rows of a given DataFrame.

In [8]:
df.head(3)

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes

###Q8 Write a Python program to select the 'name' and 'score' columns from the following
DataFrame.

In [10]:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew',
'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
df=pd.DataFrame(exam_data,index=labels)
df[['name','score']]

        name  score
a  Anastasia   12.5
b       Dima    9.0
c  Katherine   16.5
d      James    NaN
e      Emily    9.0
f    Michael   20.0
g    Matthew   14.5
h      Laura    NaN
i      Kevin    8.0
j      Jonas   19.0

###Q9 Write a Python program to select the specified columns and rows from a given data
frame

In [11]:
exam_data  = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
        'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
        'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(exam_data , index=labels)
df.iloc[[1, 3, 5, 6], [1, 3]]

   score qualify
b    9.0      no
d    NaN      no
f   20.0     yes
g   14.5     yes

###Q10 Write a Python program to select the rows where the number of attempts in the
examination is greater than 2.

In [18]:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew',
'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
df = pd.DataFrame(exam_data , index=labels)
df[df['attempts']>2]

      name  score  attempts qualify
b     Dima    9.0         3      no
d    James    NaN         3      no
f  Michael   20.0         3     yes

###Q11 Write a Python program to count the number of rows and columns of a DataFrame

In [13]:
print(len(df))
print(len(df.columns))

10
4

###Q12 Write a Python program to select the rows where the score is missing, i.e. is NaN.

In [20]:
print(df[df['score'].isna()])

    name  score  attempts qualify
d  James    NaN         3      no
h  Laura    NaN         1      no

###Q13 Write a Python program to select the rows where number of attempts in the
examination is less than 2 and score greater than 15.

In [22]:
df[(df['attempts']<2) & (df['score']>15)]

    name  score  attempts qualify
j  Jonas   19.0         1     yes

###Q14 Write a Python program to change the score in row 'd' to 11.5.

In [25]:
df.loc['d', 'score'] = 11.5
df

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James   11.5         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes

###Q15  Write a Python program to calculate the sum of the examination attempts by the
students.

In [26]:
df['attempts'].sum()

np.int64(19)

###Q16 Write a Python program to calculate the mean score for each different student in
DataFrame

In [31]:
ans = df['score'].mean
ans

<bound method Series.mean of a    12.5
b     9.0
c    16.5
d    11.5
e     9.0
f    20.0
g    14.5
h     NaN
i     8.0
j    19.0
Name: score, dtype: float64>

###Q17 Write a Python program to append a new row 'k' to data frame with given values for
each column. Now delete the new row and return the original DataFrame.

In [33]:
df.loc['K'] = [1, 'Suresh', 'yes', 15.5]
print(df)
df = df.drop('K')
print(df)

        name   score attempts qualify
a  Anastasia    12.5        1     yes
b       Dima     9.0        3      no
c  Katherine    16.5        2     yes
d      James    11.5        3      no
e      Emily     9.0        2      no
f    Michael    20.0        3     yes
g    Matthew    14.5        1     yes
h      Laura     NaN        1      no
i      Kevin     8.0        2      no
j      Jonas    19.0        1     yes
K          1  Suresh      yes    15.5
        name score attempts qualify
a  Anastasia  12.5        1     yes
b       Dima   9.0        3      no
c  Katherine  16.5        2     yes
d      James  11.5        3      no
e      Emily   9.0        2      no
f    Michael  20.0        3     yes
g    Matthew  14.5        1     yes
h      Laura   NaN        1      no
i      Kevin   8.0        2      no
j      Jonas  19.0        1     yes

###Q18  Write a Python program to sort the DataFrame first by 'name' in descending order,
then by 'score' in ascending order.

In [ ]:
df=df.sort_values(by='name')
print(df)
df=df.sort_values(by='name',ascending=-1)
print(df)

        name score attempts qualify
a  Anastasia  12.5        1     yes
b       Dima   9.0        3      no
e      Emily   9.0        2      no
d      James  11.5        3      no
j      Jonas  19.0        1     yes
c  Katherine  16.5        2     yes
i      Kevin   8.0        2      no
h      Laura   NaN        1      no
g    Matthew  14.5        1     yes
f    Michael  20.0        3     yes
        name score attempts qualify
a  Anastasia  12.5        1     yes
b       Dima   9.0        3      no
e      Emily   9.0        2      no
d      James  11.5        3      no
j      Jonas  19.0        1     yes
c  Katherine  16.5        2     yes
i      Kevin   8.0        2      no
h      Laura   NaN        1      no
g    Matthew  14.5        1     yes
f    Michael  20.0        3     yes

###Q19 Write a Python program to replace the 'qualify' column contains the values 'yes' and
'no' with True and False

In [40]:
df['qualify'] = df['qualify'].replace({'yes': True, 'no': False})
df

/var/folders/8y/st09g56d7_zdd67wcxcy08v80000gn/T/ipykernel_6297/838842287.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['qualify'] = df['qualify'].replace({'yes': True, 'no': False})

        name score attempts  qualify
a  Anastasia  12.5        1     True
b       Dima   9.0        3    False
e      Emily   9.0        2    False
d      James  11.5        3    False
j      Jonas  19.0        1     True
c  Katherine  16.5        2     True
i      Kevin   8.0        2    False
h      Laura   NaN        1    False
g    Matthew  14.5        1     True
f    Michael  20.0        3     True

###Q20 Write a Python program to delete the 'attempts' column from the DataFrame

In [43]:
df=df.drop('attempts',axis=1)
df

        name score  qualify
a  Anastasia  12.5     True
b       Dima   9.0    False
e      Emily   9.0    False
d      James  11.5    False
j      Jonas  19.0     True
c  Katherine  16.5     True
i      Kevin   8.0    False
h      Laura   NaN    False
g    Matthew  14.5     True
f    Michael  20.0     True

###Q21  Write a Python program to insert a new column in existing DataFrame

In [45]:
city = ['AA','BB','CC','DD','EE','FF','GG','HH','II','JJ']
df['city'] = city
df

        name score  qualify   color city
a  Anastasia  12.5     True     Red   AA
b       Dima   9.0    False    Blue   BB
e      Emily   9.0    False  Orange   CC
d      James  11.5    False     Red   DD
j      Jonas  19.0     True   White   EE
c  Katherine  16.5     True   White   FF
i      Kevin   8.0    False    Blue   GG
h      Laura   NaN    False   Green   HH
g    Matthew  14.5     True   Green   II
f    Michael  20.0     True     Red   JJ

###Q22 Write a Python program to iterate over rows in a DataFrame

In [46]:
for index, row in df.iterrows():
    print(row['name'], row['score'])

Anastasia 12.5
Dima 9.0
Emily 9.0
James 11.5
Jonas 19.0
Katherine 16.5
Kevin 8.0
Laura nan
Matthew 14.5
Michael 20.0

###Q23 Write a Python program to get list from DataFrame column headers

In [47]:
df.columns.tolist()

['name', 'score', 'qualify', 'color', 'city']